name: CI/CD Process
on:
  workflow_call:
  workflow_dispatch:

jobs:
  check:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        java-version:
          - 11
          - 17
          - 18
        jdk-dist:
          - adopt-hotspot
          - temurin
    runs-on: ${{ matrix.os }}
    name: Run tests via ${{ matrix.jdk-dist }} JDK v${{ matrix.java-version }}, on ${{ matrix.os }}
    steps:
      - name: Set ${{ matrix.jdk-dist }} JDK v${{ matrix.java-version }}
        uses: olafurpg/setup-scala@v14
        with:
          java-version: ${{ matrix.java-version }}
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Test native library
        run: sbt cargoTest
      - name: Build native library
        run: sbt cargoBuild
      - name: Run Scala tests
        run: sbt test

  success:
    runs-on: ubuntu-latest
    needs:
      - check
    if: >-
      always() && (
        contains(join(needs.*.result, ','), 'failure')
        || !contains(join(needs.*.result, ','), 'cancelled')
      )
    steps:
      - name: Verify that there were no failures
        run: ${{ !contains(join(needs.*.result, ','), 'failure') }}