name: CI/CD Process
on:
  workflow_call:
  workflow_dispatch:

jobs:
  check:
    strategy:
      matrix:
        os:
          - ubuntu-latest
        java-version:
          - 18
        jdk-dist:
          - adopt-hotspot
          - temurin
    runs-on: ${{ matrix.os }}
    name: Run tests via ${{ matrix.jdk-dist }} JDK v${{ matrix.java-version }}, on ${{ matrix.os }}
    steps:
      - name: Set ${{ matrix.jdk-dist }} JDK v${{ matrix.java-version }}
        uses: olafurpg/setup-scala@v14
        with:
          java-version: ${{ matrix.java-version }}
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Test native library
        run: sbt cargoTest
      - name: Build native library
        run: sbt cargoBuild && sudo cp native/target/release/librufi_core_wrapper.so /lib
      - name: Run Scala tests
        run: sbt test

  test-release:
    name: Test Release
    needs:
      - check
    runs-on: ubuntu-latest
    if: >-
      !github.event.repository.fork
      && (
        github.event_name != 'pull_request'
        || github.event.pull_request.head.repo.full_name == github.repository
      )
    concurrency:
      group: test-release-${{ github.event.number || github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Setup Scala
        uses: olafurpg/setup-scala@v14
        with:
          java-version: '17'
      - name: Build native library
        run: sbt cargoBuild && sudo cp native/target/release/librufi_core_wrapper.so /lib
      - name: Sbt check publish artifacts
        run: sbt publishLocal

  build-native-library-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Build native library
        run: cd native && cargo build --release
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: native-library
          path: native/target/release/*.so

  build-native-library-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Build native library
        run: cd native && cargo build --release
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: native-library
          path: native/target/release/*.dylib

  build-native-library-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Build native library
        run: cd native && cargo build --release
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: native-library
          path: native\target\release\*.dll

  test-job:
    needs:
      - build-native-library-linux
      - build-native-library-macos
      - build-native-library-windows
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Test build-native-library job
        uses: actions/download-artifact@v3
        with:
          name: native-library
      - name: Display structure of downloaded files
        run: ls -R

  release:
    if: github.event_name == 'push'
    needs:
      - check
      - test-release
    runs-on: ubuntu-latest
    concurrency:
      group: release
      cancel-in-progress: false
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
          token: ${{ secrets.GH_ACCESS_TOKEN }}
      - name: Setup Scala
        uses: olafurpg/setup-scala@v14
        with:
          java-version: '17'
      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm install
          npx semantic-release

  success:
    runs-on: ubuntu-latest
    needs:
      - check
      - test-release
      - release
    if: >-
      always() && (
        contains(join(needs.*.result, ','), 'failure')
        || !contains(join(needs.*.result, ','), 'cancelled')
      )
    steps:
      - name: Verify that there were no failures
        run: ${{ !contains(join(needs.*.result, ','), 'failure') }}